In [12]:
#collect sonar data
#pre processing data
#split into training and testing data
#feed it into logistic regression model
#Logistic Regression model-binary classification- to predict if it is a rock or a mine
#submarine goes over a water body, send out signals, using the SONAR data predict if the object detected is a rock or a mine

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
dataset=pd.read_csv("/content/Copy of sonar data.csv")

In [51]:
dataset #columns represent the angles, for each observation based on the transmission at an angle, it is classified as a rock or a mine the data values represent the energy within a particular frequency band between 0.0 to 0.10

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
203,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
204,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
205,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
206,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
from sklearn.metrics import accuracy_score

Data Preprocessing

In [19]:
dataset.head()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R

In [21]:
#number of rows and columns
dataset.shape

(207, 61)

In [22]:
dataset.describe()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,...,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000
mean,0.029208,0.038443,0.043837,0.054053,0.075105,0.104599,0.121591,0.134677,0.177361,0.208245,...,0.016034,0.013472,0.010729,0.010917,0.009300,0.008181,0.007771,0.007947,0.007936,0.006523
std,0.023038,0.033040,0.038521,0.046583,0.055669,0.059247,0.061897,0.085340,0.118311,0.134741,...,0.012027,0.009628,0.007071,0.007310,0.007103,0.005719,0.005756,0.006485,0.006196,0.005038
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013300,0.016400,0.018900,0.024450,0.037700,0.066950,0.080600,0.080350,0.096750,0.111150,...,0.008350,0.007350,0.005050,0.005350,0.004100,0.004400,0.003700,0.003600,0.003650,0.003100
50%,0.022800,0.030800,0.034200,0.044100,0.062000,0.092100,0.105600,0.111900,0.152200,0.181000,...,0.013800,0.011500,0.009600,0.009300,0.007500,0.006800,0.005900,0.005800,0.006300,0.005300
75%,0.035800,0.048100,0.058200,0.065700,0.101050,0.134150,0.153050,0.169800,0.231500,0.269000,...,0.020700,0.016750,0.014900,0.014450,0.012100,0.010350,0.010350,0.010400,0.010350,0.008550
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [27]:
x=dataset.iloc[:,:-1].values

In [28]:
y=dataset.iloc[:,-1].values

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [40]:
classifier=LogisticRegression()

In [41]:
y_train

array(['M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'R',
       'R', 'M', 'M', 'M', 'M', 'M', 'M', 'R', 'R', 'R', 'R', 'R', 'R',
       'M', 'R', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'R',
       'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'M',
       'R', 'R', 'M', 'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'M',
       'R', 'R', 'R', 'R', 'R', 'M', 'R', 'M', 'R', 'R', 'M', 'M', 'M',
       'R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'R',
       'R', 'R', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'R', 'M', 'R',
       'M', 'M', 'R', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'R',
       'R', 'M', 'R', 'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R',
       'R', 'R', 'M', 'M', 'R', 'M', 'M', 'R', 'M'], dtype=object)

In [42]:
x_train

array([[0.0116, 0.0179, 0.0449, ..., 0.0054, 0.0148, 0.0092],
       [0.0392, 0.0108, 0.0267, ..., 0.0044, 0.0022, 0.0014],
       [0.0286, 0.0453, 0.0277, ..., 0.0027, 0.0051, 0.0062],
       ...,
       [0.0363, 0.0478, 0.0298, ..., 0.0114, 0.0073, 0.0033],
       [0.019 , 0.0038, 0.0642, ..., 0.0022, 0.0055, 0.0122],
       [0.0329, 0.0216, 0.0386, ..., 0.0042, 0.0053, 0.0074]])

In [43]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'],
      dtype=object)

In [44]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [45]:
y_pred=classifier.predict(x_test)

In [46]:
y_pred

array(['R', 'M', 'R', 'R', 'R', 'M', 'M', 'M', 'R', 'M', 'R', 'M', 'R',
       'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'M', 'M', 'R',
       'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'M', 'M', 'M', 'R',
       'M', 'M', 'R'], dtype=object)

In [48]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['R' 'R']
 ['M' 'R']
 ['R' 'R']
 ['R' 'R']
 ['R' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['M' 'R']
 ['R' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'R']
 ['R' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']]

In [49]:
accuracy=accuracy_score(y_test,y_pred)

In [50]:
accuracy

0.7619047619047619

In [52]:
from sklearn.metrics import confusion_matrix

In [54]:
cm=confusion_matrix(y_pred,y_test)

In [55]:
cm

array([[18,  6],
       [ 4, 14]])